# Generated by Django 4.2.4 on 2024-02-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=20)),
                ('save_date', models.DateTimeField(verbose_name='saved at')),
                ('workspace_state', models.TextField()),
            ],
        ),
    ]
